### PR TITLE
CGPROD-2507_Achievement-Indicator-Not-Vanishing

### PR DESCRIPTION
**Pull request by Leonie-**
Adds a signal to update the achievements indicator when a notification has been fired. This will hopefully ensure that the notification is always cleared when there is a string of achievement notifications.

Screen Shot 2020-06-26 at 12 45 14 pm

### CODE REVIEW

**Comment by AdamXA** [comment]
Is the old one still there? https://github.com/bbc/childrens-games-genie/blob/703a471215d3ed862855576907ec466248d623c7/src/core/layout/gel-defaults.js#L242

**Comment by Leonie-** [comment]
This one is still needed to update when the achievements summary is opened/closed. The one I have added is for it to update when the toast notification finishes. This means that when a toast fires when the achievements summary is open, the indicator gets updated.

**Comment by AdamXA** [comment]
> The old one is still needed to update when the achievements summary is opened. The one I have added is for it to update when the toast notification finishes. This means that when a toast fires when the achievements summary is open, the indicator gets updated, which it didn't previously, hence the need to open it twice.

ahhh ok makes sense

**Comment by Leonie-** [comment]
Having issue with the build job webhooks, but passing build is here: https://ci-games.tools.bbc.co.uk/job/childrens-genie-pull-request/1568/

**Pull request merged**
